apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.poccccMicroservice.imagePullSecrets.name }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  {{ template "poc-ccc.imagePullSecretsData" }}