apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: poc-ccc-nfs-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-storage-class