# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.poccccMicroservice.ingress.name }}
spec:
  ingressClassName: {{ .Values.poccccMicroservice.ingress.ingressClassName }}
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /upload
        backend:
          serviceName: {{ .Values.poccccMicroservice.ingress.service }}
          servicePort: {{ .Values.poccccMicroservice.ingress.port }}
