apiVersion: v1
kind: Service
metadata:
  name: poc-ccc-microservice-service
spec:
  selector:
    app: poc-ccc-microservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: NodePort